import Head from 'next/head'
import Image from 'next/image'
import Hero from '@/Components/Hero/Hero'
import Popular from '@/Components/Popular'
import { Offers } from '@/Components/Offers'
import { NewCollections } from '@/Components/NewCollections'
import { NewsLetter } from '@/Components/NewsLetter'

export default function Home() {

  console.log('in the index')

  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Hero />
      <Popular />
      <Offers />
      <NewCollections />
      <NewsLetter />
    </>
  )
}
